version: '3'
services:
  prometheus-server:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana-ui:
    image: grafana/grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=ceseda123
      - GF_SECURITY_ADMIN_USER=admin
    links:
      - prometheus-server:prometheus
    restart: unless-stopped