global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'iaposte-backend'
    static_configs:
      - targets: ['backend:8000']
  
  - job_name: 'iaposte-frontend'
    static_configs:
      - targets: ['frontend:3000']
